### ISSUE TITLE
 valac 0.39.92 error: The name `Priority' does not exist in the context of `Drt.System.make_directory_with_parents_async' 

### ISSUE THREAD

**Issue by martinkg** [tiliado/diorite#22] opened 2018-03-15 10:16 UTC
Hi,

when compiling diorite-4.10.0 on Fedora 28 i get the following error messages:
[diorite-4_10_0-build-f28.log](https://martinkg.fedorapeople.org/Packages/nuvolaruntime/diorite-4_10_0-build-f28.log)

**Comment by fenryxo** [comment] 2018-03-15 11:10
Closing as a duplicate of #19. Next time when I ask you to attach logs as text files, please do so instead of linking logs elsewhere. 

![github_attach](https://user-images.githubusercontent.com/853706/37459547-bba911c0-2848-11e8-80b6-5743cbda90c1.png)

**Closed by fenryxo** 2018-03-15 11:10 UTC
